### PR TITLE
Added a simple installer script

### PR DESCRIPTION
**Pull request by GabrielGavrilov**
The first I tried to use YMusicDL, it took me quite some time finding which tools it uses and where to install them. So I just made a simple installer script that makes it easier for people  to install yt-dlp and ffmpeg. 

Note: the installer does not include mp3gain because I've never felt the need to use it, and I don't know where I could go to install it for my windows machine.

### CODE REVIEW

**Comment by wascup** [comment]
I would also prefer to have the installer in the main.js, you can add `https` for a dependency use `child_process` to see if its installed and download yt-dlp from `https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe` using `https` response pipe.
As for mp3gain I wont worry about it right now
also change it to download yt-dlp into /bin folder
*for linux just download `https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux`*

**Comment by GabrielGavrilov** [comment]
I tried to write the installer script in JavaScript first, but I'm unable to store the shell command output in a variable properly due to it being asynchronous. Every time I store it in a variable it just prints the async promise. 

I tried every response on this stack question, but I'm still getting the same issue https://stackoverflow.com/questions/12941083/execute-and-get-the-output-of-a-shell-command-in-node-js

If you're fine with the installer written in python, I could modify it to suite your preferences.
If you want me to write it in javascript (I actually prefer it in js over python) then how would I store the output in a variable and avoid the promise async response?

**Comment by wascup** [comment]
I will accept it for now but later I will write the installer in the main.js file

**Comment by GabrielGavrilov** [comment]
Can I ask why? I understand writing it in JavaScript, but writing it in main.js is just plain unnecessary. Wouldn't writing a separate installer.js program and adding a "npm run install" script in the package be more practical?

**Comment by wascup** [comment]
i will make it a module, but the reason is because i will eventually export this project to a .exe file and dont want any other instructions besides: run exe, and everything works

**Comment by GabrielGavrilov** [comment]
I saw the messages on discord, you know you could of just said you didn't want my help lol, you don't have to push my pull requests out of pitty

**Comment by GabrielGavrilov** [comment]
Thanks for explaining, I was just curious because I never worked with electron before

**Comment by wascup** [comment]
It's cool just kinda was weird that after not speaking for almost a year, ye sent a pull request

**Comment by GabrielGavrilov** [comment]
haha yea I guess its pretty weird. Levi worked on my dads car the other day and we've started talking again

**Pull request merged**
